[project]
name = 'Global-Water-Quality-Monitoring'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.alert-system]
path = 'contracts/alert-system.clar'
clarity_version = 2
epoch = 2.5

[contracts.data-analysis]
path = 'contracts/data-analysis.clar'
clarity_version = 2
epoch = 2.5

[contracts.sensor-network]
path = 'contracts/sensor-network.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
